language: node_js
node_js:
- node
- '6'
before_script:
- npm install -g gulp
install:
- npm install
env:
  matrix:
    secure: aC+e2vnd2f1UAEvNsysD1gAy3QL6IRsC2h0B6wdI7VdLy06tcUhb8yZk8fwsGYxUf9EEOArHt5VukzFgEg398EN8/xCRjM6QDllkY9U0VLkLXj2hrm6aucBD+XpKdqwsguLiEyPHknMb1AFfz0ViJxctTVpM6EJQ4OyPvNciTkwtdmDRtU2+7vr+8pcPfe35mbKzvTHlgnn5QZX/8yHE3tH4v9MDoRF+kLDntS0x5s7Rd8vsIIqyVC1OQLGfQfiayCEB+VVhe2w1Z8VvBXQSPTUYET5/KTrOaCXuq70QIadyhuvDRIBpv6U6Cvg5IlyUEj0jpyih+Bzz5S8ZKjI3f+/wU82VgWe9vlHkLpVlclvjByz5uJM/aYBmc1UCttw2r3HrwrzgghvFDjzOAIJvDRqXcTvuDiAuN2TSxDUmsWEIYQ8F/GVKUttxHKZB6LmD0tDjXMASZBDDXA3OFRiOdhpFTXD4FuHQ1pqI0PnuNg7ku7peMgn8TgOLYB3iTGaC8BWPbF0UK3UsxqYs0LF+xMeBJiztUem5aChCkSvVVx7aW7UrmNKUYauGAUrinaFoM7ryh+tN/OB7iwv02aAH/pGWB1is8F0+60DkopeyEFgI+E8iOBZD17y2oFn8OPp+w1F7155hPSJxlkmt271E+bN6Hw1Y7tmNKr1aU7ss0lU=
